[workspace]

members = [
	"crates/dlog-sigma-primitives",
	"crates/dlog-group"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [
	"Mario Scuro <mscuro@fbk.eu>"
	]
repository = "https://github.com/aleph-fbk/pet-crypto-primitives-rs"
documentation = "https://aleph-fbk.github.io/pet-crypto-primitives-rs"
readme = "README.md"
keywords = ["cryptography", "homomorphic", "ecc", "zero-knowledge"]
categories = ["cryptography"]
rust-version = "1.74"

[workspace.dependencies]

# Curves (RustCrypto + Dalek) -- Note that only one curve should be used
k256 = { version = "0.13.4", features = ["arithmetic"] }   # secp256k1 
p256 = { version = "0.13.2", features = ["arithmetic"] } # NIST 
p384 = { version = "0.13.1", features = ["arithmetic"] }   # NIST
curve25519-dalek = { version = "4.1.3", features = ["rand_core"] } # Curve25519/Ristretto 
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["rand_core"] } # Ed25519 sigs 

# Serde / encoding
serde = { version = "1", default-features = false, features = ["derive","alloc"] }
serde_json = "1"                                                                  
base64ct = { version = "1.8.0", default-features = false, features = ["alloc"] }  
zeroize = { version = "1.8.1", default-features = false, features = ["alloc"] }   
merlin = {version = "3.0.0"}

# Randomness
rand_core = "0.6.4"   # version used in the EC implementations                                           
rand_chacha = { version = "0.3.1", default-features = false }    
rand = { version = "^0.8", default-features = true }            # only used in tests

# Hashes
sha3 = "0.10.8"

# Benchmarks
criterion = "^0.7.0" 

